#!/usr/bin/python

import sys

mylist = sys.stdin.readline().split()

max = 0
min = int(mylist[0])
for i in mylist:
    if int(i) > max:
        max = int(i)

    if int(i) < min:
        min = int(i)
print max, min
