#!/usr/bin/python

import sys

vowels = ['a', 'e', 'i', 'o', 'u', 'y']

count = sys.stdin.readline()

for i in range(int(count)):
    line = sys.stdin.readline()
    vowel_count=0
    for c in line:
        if c in vowels:
            vowel_count += 1
    print vowel_count,
    
