#!/usr/bin/python

import sys

count = int(sys.stdin.readline())

for i in range(count):
    vals = sys.stdin.readline().split()[:-1:]
    val_int = [int(x) for x in vals]
    mean =  float(sum(val_int)) / len(vals)
    print int(round(mean)),
